// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agentlink/v1/agentlink.proto

package agentlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMsg_Hello
	//	*AgentMsg_Heartbeat
	//	*AgentMsg_Event
	//	*AgentMsg_Log
	//	*AgentMsg_Pull
	//	*AgentMsg_Ack
	Msg           isAgentMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMsg) Reset() {
	*x = AgentMsg{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMsg) ProtoMessage() {}

func (x *AgentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMsg.ProtoReflect.Descriptor instead.
func (*AgentMsg) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMsg) GetMsg() isAgentMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMsg) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMsg) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMsg) GetEvent() *ServerEvent {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *AgentMsg) GetLog() *LogChunk {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *AgentMsg) GetPull() *PullReport {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_Pull); ok {
			return x.Pull
		}
	}
	return nil
}

func (x *AgentMsg) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isAgentMsg_Msg interface {
	isAgentMsg_Msg()
}

type AgentMsg_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // first message in the stream
}

type AgentMsg_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMsg_Event struct {
	Event *ServerEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type AgentMsg_Log struct {
	Log *LogChunk `protobuf:"bytes,4,opt,name=log,proto3,oneof"` // response to TailLogs
}

type AgentMsg_Pull struct {
	Pull *PullReport `protobuf:"bytes,5,opt,name=pull,proto3,oneof"` // progress/result of PrePull
}

type AgentMsg_Ack struct {
	Ack *Ack `protobuf:"bytes,6,opt,name=ack,proto3,oneof"` // confirms a master command by cmd_id
}

func (*AgentMsg_Hello) isAgentMsg_Msg() {}

func (*AgentMsg_Heartbeat) isAgentMsg_Msg() {}

func (*AgentMsg_Event) isAgentMsg_Msg() {}

func (*AgentMsg_Log) isAgentMsg_Msg() {}

func (*AgentMsg_Pull) isAgentMsg_Msg() {}

func (*AgentMsg_Ack) isAgentMsg_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeToken     string                 `protobuf:"bytes,1,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	CapacitySlots int32                  `protobuf:"varint,4,opt,name=capacity_slots,json=capacitySlots,proto3" json:"capacity_slots,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Servers       []*ServerState         `protobuf:"bytes,6,rep,name=servers,proto3" json:"servers,omitempty"` // recovered map after agent restart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Hello) GetCapacitySlots() int32 {
	if x != nil {
		return x.CapacitySlots
	}
	return 0
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetServers() []*ServerState {
	if x != nil {
		return x.Servers
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs      int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	Node          *NodeStats             `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Servers       []*ServerState         `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *Heartbeat) GetNode() *NodeStats {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Heartbeat) GetServers() []*ServerState {
	if x != nil {
		return x.Servers
	}
	return nil
}

type NodeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float32                `protobuf:"fixed32,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemUsed       uint64                 `protobuf:"varint,2,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	MemTotal      uint64                 `protobuf:"varint,3,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	DiskUsed      uint64                 `protobuf:"varint,4,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	DiskTotal     uint64                 `protobuf:"varint,5,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	Load1         float32                `protobuf:"fixed32,6,opt,name=load1,proto3" json:"load1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStats) Reset() {
	*x = NodeStats{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStats) ProtoMessage() {}

func (x *NodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStats.ProtoReflect.Descriptor instead.
func (*NodeStats) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStats) GetCpu() float32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *NodeStats) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *NodeStats) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *NodeStats) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *NodeStats) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *NodeStats) GetLoad1() float32 {
	if x != nil {
		return x.Load1
	}
	return 0
}

type ServerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // pulling|starting|ready|allocated|draining|stopped|failed
	Players       int32                  `protobuf:"varint,3,opt,name=players,proto3" json:"players,omitempty"`
	TickMs        float32                `protobuf:"fixed32,4,opt,name=tick_ms,json=tickMs,proto3" json:"tick_ms,omitempty"`
	MatchId       string                 `protobuf:"bytes,5,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{4}
}

func (x *ServerState) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ServerState) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *ServerState) GetTickMs() float32 {
	if x != nil {
		return x.TickMs
	}
	return 0
}

func (x *ServerState) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ServerState) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerState) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ServerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // failed|oom|ready|match_start|match_end
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{5}
}

func (x *ServerEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ServerEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"` // TailLogs command this chunk answers
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"` // no more chunks will follow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{6}
}

func (x *LogChunk) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *LogChunk) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type PullReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"` // PrePull command this report answers
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // pulling|pulled|failed
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"` // progress info or error text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullReport) Reset() {
	*x = PullReport{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullReport) ProtoMessage() {}

func (x *PullReport) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullReport.ProtoReflect.Descriptor instead.
func (*PullReport) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{7}
}

func (x *PullReport) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *PullReport) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *PullReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PullReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

type MasterMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MasterMsg_Start
	//	*MasterMsg_Stop
	//	*MasterMsg_Prepull
	//	*MasterMsg_Drain
	//	*MasterMsg_Upgrade
	//	*MasterMsg_Tail
	//	*MasterMsg_Ack
	//	*MasterMsg_Allocate
	Msg           isMasterMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMsg) Reset() {
	*x = MasterMsg{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMsg) ProtoMessage() {}

func (x *MasterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMsg.ProtoReflect.Descriptor instead.
func (*MasterMsg) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{9}
}

func (x *MasterMsg) GetMsg() isMasterMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MasterMsg) GetStart() *StartServer {
	if x != nil {
		if x, ok := x.Msg.(*MasterMsg_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *MasterMsg) GetStop() *StopServer {
	if x != nil {
		if x, ok := x.Msg.(*MasterMsg_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *MasterMsg) GetPrepull() *PrePull {
	if x != nil {
		if x, ok := x.Msg.(*MasterMsg_Prepull); ok {
			return x.Prepull
		}
	}
	return nil
}

func (x *MasterMsg) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Msg.(*MasterMsg_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *MasterMsg) GetUpgrade() *UpgradeAgent {
	if x != nil {
		if x, ok := x.Msg.(*MasterMsg_Upgrade); ok {
			return x.Upgrade
		}
	}
	return nil
}

func (x *MasterMsg) GetTail() *TailLogs {
	if x != nil {
		if x, ok := x.Msg.(*MasterMsg_Tail); ok {
			return x.Tail
		}
	}
	return nil
}

func (x *MasterMsg) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*MasterMsg_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *MasterMsg) GetAllocate() *AllocateServer {
	if x != nil {
		if x, ok := x.Msg.(*MasterMsg_Allocate); ok {
			return x.Allocate
		}
	}
	return nil
}

type isMasterMsg_Msg interface {
	isMasterMsg_Msg()
}

type MasterMsg_Start struct {
	Start *StartServer `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type MasterMsg_Stop struct {
	Stop *StopServer `protobuf:"bytes,2,opt,name=stop,proto3,oneof"`
}

type MasterMsg_Prepull struct {
	Prepull *PrePull `protobuf:"bytes,3,opt,name=prepull,proto3,oneof"`
}

type MasterMsg_Drain struct {
	Drain *Drain `protobuf:"bytes,4,opt,name=drain,proto3,oneof"` // node-level: stop creating, let matches finish
}

type MasterMsg_Upgrade struct {
	Upgrade *UpgradeAgent `protobuf:"bytes,5,opt,name=upgrade,proto3,oneof"`
}

type MasterMsg_Tail struct {
	Tail *TailLogs `protobuf:"bytes,6,opt,name=tail,proto3,oneof"`
}

type MasterMsg_Ack struct {
	Ack *Ack `protobuf:"bytes,7,opt,name=ack,proto3,oneof"` // reserved for master-side acknowledgements
}

type MasterMsg_Allocate struct {
	Allocate *AllocateServer `protobuf:"bytes,8,opt,name=allocate,proto3,oneof"` // iteration 2: deliver a match to the dedik
}

func (*MasterMsg_Start) isMasterMsg_Msg() {}

func (*MasterMsg_Stop) isMasterMsg_Msg() {}

func (*MasterMsg_Prepull) isMasterMsg_Msg() {}

func (*MasterMsg_Drain) isMasterMsg_Msg() {}

func (*MasterMsg_Upgrade) isMasterMsg_Msg() {}

func (*MasterMsg_Tail) isMasterMsg_Msg() {}

func (*MasterMsg_Ack) isMasterMsg_Msg() {}

func (*MasterMsg_Allocate) isMasterMsg_Msg() {}

// AllocateServer tells the node's agent that master allocated a match to
// server_id: the agent forwards the `allocated{match_id, players_expected}`
// frame to liba over the per-server socket (docs/specs/protocol.md §2) and
// remembers it for liba reconnect replay. Sent after every successful
// allocation — both REST POST /v1/allocate and the built-in matchmaker.
// players_expected = 0 means "unknown" (external matchmaker did not say).
type AllocateServer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CmdId           string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	ServerId        string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MatchId         string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayersExpected int32                  `protobuf:"varint,4,opt,name=players_expected,json=playersExpected,proto3" json:"players_expected,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocateServer) Reset() {
	*x = AllocateServer{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateServer) ProtoMessage() {}

func (x *AllocateServer) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateServer.ProtoReflect.Descriptor instead.
func (*AllocateServer) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{10}
}

func (x *AllocateServer) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *AllocateServer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AllocateServer) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *AllocateServer) GetPlayersExpected() int32 {
	if x != nil {
		return x.PlayersExpected
	}
	return 0
}

type StartServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limits        *Limits                `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"` // 0 → agent picks a port from its pool
	CmdId         string                 `protobuf:"bytes,6,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServer) Reset() {
	*x = StartServer{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServer) ProtoMessage() {}

func (x *StartServer) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServer.ProtoReflect.Descriptor instead.
func (*StartServer) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{11}
}

func (x *StartServer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *StartServer) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *StartServer) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartServer) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *StartServer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartServer) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

type Limits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillis     int32                  `protobuf:"varint,1,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemMb         int32                  `protobuf:"varint,2,opt,name=mem_mb,json=memMb,proto3" json:"mem_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{12}
}

func (x *Limits) GetCpuMillis() int32 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *Limits) GetMemMb() int32 {
	if x != nil {
		return x.MemMb
	}
	return 0
}

type StopServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	GraceS        int32                  `protobuf:"varint,2,opt,name=grace_s,json=graceS,proto3" json:"grace_s,omitempty"`
	CmdId         string                 `protobuf:"bytes,3,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServer) Reset() {
	*x = StopServer{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServer) ProtoMessage() {}

func (x *StopServer) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServer.ProtoReflect.Descriptor instead.
func (*StopServer) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{13}
}

func (x *StopServer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *StopServer) GetGraceS() int32 {
	if x != nil {
		return x.GraceS
	}
	return 0
}

func (x *StopServer) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

type PrePull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePull) Reset() {
	*x = PrePull{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePull) ProtoMessage() {}

func (x *PrePull) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePull.ProtoReflect.Descriptor instead.
func (*PrePull) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{14}
}

func (x *PrePull) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *PrePull) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{15}
}

func (x *Drain) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *Drain) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpgradeAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeAgent) Reset() {
	*x = UpgradeAgent{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeAgent) ProtoMessage() {}

func (x *UpgradeAgent) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeAgent.ProtoReflect.Descriptor instead.
func (*UpgradeAgent) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{16}
}

func (x *UpgradeAgent) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *UpgradeAgent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpgradeAgent) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UpgradeAgent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TailLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogs) Reset() {
	*x = TailLogs{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogs) ProtoMessage() {}

func (x *TailLogs) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogs.ProtoReflect.Descriptor instead.
func (*TailLogs) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{17}
}

func (x *TailLogs) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *TailLogs) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *TailLogs) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

var File_agentlink_v1_agentlink_proto protoreflect.FileDescriptor

const file_agentlink_v1_agentlink_proto_rawDesc = "" +
	"\n" +
	"\x1cagentlink/v1/agentlink.proto\x12\fagentlink.v1\"\xad\x02\n" +
	"\bAgentMsg\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.agentlink.v1.HelloH\x00R\x05hello\x127\n" +
	"\theartbeat\x18\x02 \x01(\v2\x17.agentlink.v1.HeartbeatH\x00R\theartbeat\x121\n" +
	"\x05event\x18\x03 \x01(\v2\x19.agentlink.v1.ServerEventH\x00R\x05event\x12*\n" +
	"\x03log\x18\x04 \x01(\v2\x16.agentlink.v1.LogChunkH\x00R\x03log\x12.\n" +
	"\x04pull\x18\x05 \x01(\v2\x18.agentlink.v1.PullReportH\x00R\x04pull\x12%\n" +
	"\x03ack\x18\x06 \x01(\v2\x11.agentlink.v1.AckH\x00R\x03ackB\x05\n" +
	"\x03msg\"\xdb\x01\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"node_token\x18\x01 \x01(\tR\tnodeToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12%\n" +
	"\x0ecapacity_slots\x18\x04 \x01(\x05R\rcapacitySlots\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x123\n" +
	"\aservers\x18\x06 \x03(\v2\x19.agentlink.v1.ServerStateR\aservers\"\x8b\x01\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\x12+\n" +
	"\x04node\x18\x02 \x01(\v2\x17.agentlink.v1.NodeStatsR\x04node\x123\n" +
	"\aservers\x18\x03 \x03(\v2\x19.agentlink.v1.ServerStateR\aservers\"\xa7\x01\n" +
	"\tNodeStats\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x02R\x03cpu\x12\x19\n" +
	"\bmem_used\x18\x02 \x01(\x04R\amemUsed\x12\x1b\n" +
	"\tmem_total\x18\x03 \x01(\x04R\bmemTotal\x12\x1b\n" +
	"\tdisk_used\x18\x04 \x01(\x04R\bdiskUsed\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x05 \x01(\x04R\tdiskTotal\x12\x14\n" +
	"\x05load1\x18\x06 \x01(\x02R\x05load1\"\xbc\x01\n" +
	"\vServerState\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\aplayers\x18\x03 \x01(\x05R\aplayers\x12\x17\n" +
	"\atick_ms\x18\x04 \x01(\x02R\x06tickMs\x12\x19\n" +
	"\bmatch_id\x18\x05 \x01(\tR\amatchId\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"V\n" +
	"\vServerEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"d\n" +
	"\bLogChunk\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"p\n" +
	"\n" +
	"PullReport\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\x1c\n" +
	"\x03Ack\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\"\x9e\x03\n" +
	"\tMasterMsg\x121\n" +
	"\x05start\x18\x01 \x01(\v2\x19.agentlink.v1.StartServerH\x00R\x05start\x12.\n" +
	"\x04stop\x18\x02 \x01(\v2\x18.agentlink.v1.StopServerH\x00R\x04stop\x121\n" +
	"\aprepull\x18\x03 \x01(\v2\x15.agentlink.v1.PrePullH\x00R\aprepull\x12+\n" +
	"\x05drain\x18\x04 \x01(\v2\x13.agentlink.v1.DrainH\x00R\x05drain\x126\n" +
	"\aupgrade\x18\x05 \x01(\v2\x1a.agentlink.v1.UpgradeAgentH\x00R\aupgrade\x12,\n" +
	"\x04tail\x18\x06 \x01(\v2\x16.agentlink.v1.TailLogsH\x00R\x04tail\x12%\n" +
	"\x03ack\x18\a \x01(\v2\x11.agentlink.v1.AckH\x00R\x03ack\x12:\n" +
	"\ballocate\x18\b \x01(\v2\x1c.agentlink.v1.AllocateServerH\x00R\ballocateB\x05\n" +
	"\x03msg\"\x8a\x01\n" +
	"\x0eAllocateServer\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\x12)\n" +
	"\x10players_expected\x18\x04 \x01(\x05R\x0fplayersExpected\"\x8e\x02\n" +
	"\vStartServer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x124\n" +
	"\x03env\x18\x03 \x03(\v2\".agentlink.v1.StartServer.EnvEntryR\x03env\x12,\n" +
	"\x06limits\x18\x04 \x01(\v2\x14.agentlink.v1.LimitsR\x06limits\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x15\n" +
	"\x06cmd_id\x18\x06 \x01(\tR\x05cmdId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x06Limits\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x01 \x01(\x05R\tcpuMillis\x12\x15\n" +
	"\x06mem_mb\x18\x02 \x01(\x05R\x05memMb\"Y\n" +
	"\n" +
	"StopServer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\agrace_s\x18\x02 \x01(\x05R\x06graceS\x12\x15\n" +
	"\x06cmd_id\x18\x03 \x01(\tR\x05cmdId\"=\n" +
	"\aPrePull\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\"6\n" +
	"\x05Drain\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"i\n" +
	"\fUpgradeAgent\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"V\n" +
	"\bTailLogs\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow2K\n" +
	"\tAgentLink\x12>\n" +
	"\aSession\x12\x16.agentlink.v1.AgentMsg\x1a\x17.agentlink.v1.MasterMsg(\x010\x01B8Z6github.com/ufna/birdman/proto/agentlink/v1;agentlinkv1b\x06proto3"

var (
	file_agentlink_v1_agentlink_proto_rawDescOnce sync.Once
	file_agentlink_v1_agentlink_proto_rawDescData []byte
)

func file_agentlink_v1_agentlink_proto_rawDescGZIP() []byte {
	file_agentlink_v1_agentlink_proto_rawDescOnce.Do(func() {
		file_agentlink_v1_agentlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentlink_v1_agentlink_proto_rawDesc), len(file_agentlink_v1_agentlink_proto_rawDesc)))
	})
	return file_agentlink_v1_agentlink_proto_rawDescData
}

var file_agentlink_v1_agentlink_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_agentlink_v1_agentlink_proto_goTypes = []any{
	(*AgentMsg)(nil),       // 0: agentlink.v1.AgentMsg
	(*Hello)(nil),          // 1: agentlink.v1.Hello
	(*Heartbeat)(nil),      // 2: agentlink.v1.Heartbeat
	(*NodeStats)(nil),      // 3: agentlink.v1.NodeStats
	(*ServerState)(nil),    // 4: agentlink.v1.ServerState
	(*ServerEvent)(nil),    // 5: agentlink.v1.ServerEvent
	(*LogChunk)(nil),       // 6: agentlink.v1.LogChunk
	(*PullReport)(nil),     // 7: agentlink.v1.PullReport
	(*Ack)(nil),            // 8: agentlink.v1.Ack
	(*MasterMsg)(nil),      // 9: agentlink.v1.MasterMsg
	(*AllocateServer)(nil), // 10: agentlink.v1.AllocateServer
	(*StartServer)(nil),    // 11: agentlink.v1.StartServer
	(*Limits)(nil),         // 12: agentlink.v1.Limits
	(*StopServer)(nil),     // 13: agentlink.v1.StopServer
	(*PrePull)(nil),        // 14: agentlink.v1.PrePull
	(*Drain)(nil),          // 15: agentlink.v1.Drain
	(*UpgradeAgent)(nil),   // 16: agentlink.v1.UpgradeAgent
	(*TailLogs)(nil),       // 17: agentlink.v1.TailLogs
	nil,                    // 18: agentlink.v1.StartServer.EnvEntry
}
var file_agentlink_v1_agentlink_proto_depIdxs = []int32{
	1,  // 0: agentlink.v1.AgentMsg.hello:type_name -> agentlink.v1.Hello
	2,  // 1: agentlink.v1.AgentMsg.heartbeat:type_name -> agentlink.v1.Heartbeat
	5,  // 2: agentlink.v1.AgentMsg.event:type_name -> agentlink.v1.ServerEvent
	6,  // 3: agentlink.v1.AgentMsg.log:type_name -> agentlink.v1.LogChunk
	7,  // 4: agentlink.v1.AgentMsg.pull:type_name -> agentlink.v1.PullReport
	8,  // 5: agentlink.v1.AgentMsg.ack:type_name -> agentlink.v1.Ack
	4,  // 6: agentlink.v1.Hello.servers:type_name -> agentlink.v1.ServerState
	3,  // 7: agentlink.v1.Heartbeat.node:type_name -> agentlink.v1.NodeStats
	4,  // 8: agentlink.v1.Heartbeat.servers:type_name -> agentlink.v1.ServerState
	11, // 9: agentlink.v1.MasterMsg.start:type_name -> agentlink.v1.StartServer
	13, // 10: agentlink.v1.MasterMsg.stop:type_name -> agentlink.v1.StopServer
	14, // 11: agentlink.v1.MasterMsg.prepull:type_name -> agentlink.v1.PrePull
	15, // 12: agentlink.v1.MasterMsg.drain:type_name -> agentlink.v1.Drain
	16, // 13: agentlink.v1.MasterMsg.upgrade:type_name -> agentlink.v1.UpgradeAgent
	17, // 14: agentlink.v1.MasterMsg.tail:type_name -> agentlink.v1.TailLogs
	8,  // 15: agentlink.v1.MasterMsg.ack:type_name -> agentlink.v1.Ack
	10, // 16: agentlink.v1.MasterMsg.allocate:type_name -> agentlink.v1.AllocateServer
	18, // 17: agentlink.v1.StartServer.env:type_name -> agentlink.v1.StartServer.EnvEntry
	12, // 18: agentlink.v1.StartServer.limits:type_name -> agentlink.v1.Limits
	0,  // 19: agentlink.v1.AgentLink.Session:input_type -> agentlink.v1.AgentMsg
	9,  // 20: agentlink.v1.AgentLink.Session:output_type -> agentlink.v1.MasterMsg
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_agentlink_v1_agentlink_proto_init() }
func file_agentlink_v1_agentlink_proto_init() {
	if File_agentlink_v1_agentlink_proto != nil {
		return
	}
	file_agentlink_v1_agentlink_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMsg_Hello)(nil),
		(*AgentMsg_Heartbeat)(nil),
		(*AgentMsg_Event)(nil),
		(*AgentMsg_Log)(nil),
		(*AgentMsg_Pull)(nil),
		(*AgentMsg_Ack)(nil),
	}
	file_agentlink_v1_agentlink_proto_msgTypes[9].OneofWrappers = []any{
		(*MasterMsg_Start)(nil),
		(*MasterMsg_Stop)(nil),
		(*MasterMsg_Prepull)(nil),
		(*MasterMsg_Drain)(nil),
		(*MasterMsg_Upgrade)(nil),
		(*MasterMsg_Tail)(nil),
		(*MasterMsg_Ack)(nil),
		(*MasterMsg_Allocate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentlink_v1_agentlink_proto_rawDesc), len(file_agentlink_v1_agentlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentlink_v1_agentlink_proto_goTypes,
		DependencyIndexes: file_agentlink_v1_agentlink_proto_depIdxs,
		MessageInfos:      file_agentlink_v1_agentlink_proto_msgTypes,
	}.Build()
	File_agentlink_v1_agentlink_proto = out.File
	file_agentlink_v1_agentlink_proto_goTypes = nil
	file_agentlink_v1_agentlink_proto_depIdxs = nil
}
