// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agentlink/v1/agentlink.proto

package agentlinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentLink_Session_FullMethodName = "/agentlink.v1.AgentLink/Session"
	AgentLink_Enroll_FullMethodName  = "/agentlink.v1.AgentLink/Enroll"
)

// AgentLinkClient is the client API for AgentLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentLink is the bidirectional control channel between birdman-master and
// birdman-agent. The agent dials master (outbound only, TLS) and keeps a
// single Session stream open. The first AgentMsg on the stream MUST be Hello.
//
// Delivery semantics: every command in MasterMsg carries a cmd_id; the agent
// confirms execution with Ack{cmd_id} (or a ServerEvent describing the
// failure). Master re-sends unacknowledged commands on reconnect, so command
// handling on the agent must be idempotent by cmd_id (at-least-once).
type AgentLinkClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMsg, MasterMsg], error)
	// Enroll (mTLS v1, аддитивно) — unary-обмен node_token → клиентский
	// сертификат на том же gRPC-листенере, что и Session. Это НЕ команда:
	// cmd_id/Ack/pending-машинерия не участвуют (обычный запрос-ответ).
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type agentLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLinkClient(cc grpc.ClientConnInterface) AgentLinkClient {
	return &agentLinkClient{cc}
}

func (c *agentLinkClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMsg, MasterMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLink_ServiceDesc.Streams[0], AgentLink_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMsg, MasterMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_SessionClient = grpc.BidiStreamingClient[AgentMsg, MasterMsg]

func (c *agentLinkClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, AgentLink_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentLinkServer is the server API for AgentLink service.
// All implementations must embed UnimplementedAgentLinkServer
// for forward compatibility.
//
// AgentLink is the bidirectional control channel between birdman-master and
// birdman-agent. The agent dials master (outbound only, TLS) and keeps a
// single Session stream open. The first AgentMsg on the stream MUST be Hello.
//
// Delivery semantics: every command in MasterMsg carries a cmd_id; the agent
// confirms execution with Ack{cmd_id} (or a ServerEvent describing the
// failure). Master re-sends unacknowledged commands on reconnect, so command
// handling on the agent must be idempotent by cmd_id (at-least-once).
type AgentLinkServer interface {
	Session(grpc.BidiStreamingServer[AgentMsg, MasterMsg]) error
	// Enroll (mTLS v1, аддитивно) — unary-обмен node_token → клиентский
	// сертификат на том же gRPC-листенере, что и Session. Это НЕ команда:
	// cmd_id/Ack/pending-машинерия не участвуют (обычный запрос-ответ).
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedAgentLinkServer()
}

// UnimplementedAgentLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLinkServer struct{}

func (UnimplementedAgentLinkServer) Session(grpc.BidiStreamingServer[AgentMsg, MasterMsg]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedAgentLinkServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedAgentLinkServer) mustEmbedUnimplementedAgentLinkServer() {}
func (UnimplementedAgentLinkServer) testEmbeddedByValue()                   {}

// UnsafeAgentLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLinkServer will
// result in compilation errors.
type UnsafeAgentLinkServer interface {
	mustEmbedUnimplementedAgentLinkServer()
}

func RegisterAgentLinkServer(s grpc.ServiceRegistrar, srv AgentLinkServer) {
	// If the following call pancis, it indicates UnimplementedAgentLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLink_ServiceDesc, srv)
}

func _AgentLink_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServer).Session(&grpc.GenericServerStream[AgentMsg, MasterMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_SessionServer = grpc.BidiStreamingServer[AgentMsg, MasterMsg]

func _AgentLink_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentLinkServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentLink_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentLinkServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentLink_ServiceDesc is the grpc.ServiceDesc for AgentLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentlink.v1.AgentLink",
	HandlerType: (*AgentLinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _AgentLink_Enroll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _AgentLink_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentlink/v1/agentlink.proto",
}
