// Package config loads the agent YAML config (docs/specs/agent.md §10).
//
// Unknown keys are ignored on purpose (forward compatibility): configs
// written for newer agents must stay loadable by older ones.
package config

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// Limits are per-server cgroup limits.
type Limits struct {
	CPUMillis int `yaml:"cpu_millis"`
	MemMB     int `yaml:"mem_mb"`
}

// RegistryAuth configures pulls from a private registry (GHCR).
// The token itself lives only in TokenFile — never in the config or code.
type RegistryAuth struct {
	Username  string `yaml:"username"`
	TokenFile string `yaml:"token_file"`
}

// Token reads the registry token from TokenFile. The value must never be
// logged or persisted anywhere else.
func (a *RegistryAuth) Token() (string, error) {
	b, err := os.ReadFile(a.TokenFile)
	if err != nil {
		return "", fmt.Errorf("read registry token: %w", err)
	}
	tok := strings.TrimSpace(string(b))
	if tok == "" {
		return "", fmt.Errorf("registry token file %s is empty", a.TokenFile)
	}
	return tok, nil
}

// Config is the v0 subset of /etc/birdman/agent.yaml.
//
// master_addr / node_token(_file) / tls_* power the `run` daemon mode
// (iteration 1); run-once ignores them.
type Config struct {
	Region        string        `yaml:"region"`
	CapacitySlots int           `yaml:"capacity_slots"`
	PortRange     []int         `yaml:"port_range"`
	LimitsDefault Limits        `yaml:"limits_default"`
	LogDir        string        `yaml:"log_dir"`
	DataDir       string        `yaml:"data_dir"`
	RegistryAuth  *RegistryAuth `yaml:"registry_auth"`

	// MasterAddr is the gRPC AgentLink endpoint (host:port, always TLS).
	MasterAddr string `yaml:"master_addr"`
	// NodeToken authenticates the agent in Hello (protocol.md §Auth, v0).
	// Prefer NodeTokenFile: like the registry token, the secret then lives
	// only in a 0600 file, never in the config.
	NodeToken     string `yaml:"node_token"`
	NodeTokenFile string `yaml:"node_token_file"`
	// TLSInsecure skips master certificate verification — DEV ONLY (master
	// with a self-signed autogenerated cert). Production: tls_ca_file.
	TLSInsecure bool   `yaml:"tls_insecure"`
	TLSCAFile   string `yaml:"tls_ca_file"`
}

// MasterToken returns the node token: the inline value if set, otherwise the
// contents of node_token_file. Must never be logged.
func (c *Config) MasterToken() (string, error) {
	if c.NodeToken != "" {
		return c.NodeToken, nil
	}
	if c.NodeTokenFile == "" {
		return "", fmt.Errorf("node_token or node_token_file is required")
	}
	b, err := os.ReadFile(c.NodeTokenFile)
	if err != nil {
		return "", fmt.Errorf("read node token: %w", err)
	}
	tok := strings.TrimSpace(string(b))
	if tok == "" {
		return "", fmt.Errorf("node token file %s is empty", c.NodeTokenFile)
	}
	return tok, nil
}

// ValidateRun checks the extra fields required by the `run` daemon mode.
func (c *Config) ValidateRun() error {
	if c.MasterAddr == "" {
		return fmt.Errorf("master_addr is required for run mode")
	}
	if c.NodeToken == "" && c.NodeTokenFile == "" {
		return fmt.Errorf("node_token or node_token_file is required for run mode")
	}
	return nil
}

// Load reads, defaults and validates the config at path.
func Load(path string) (*Config, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var c Config
	if err := yaml.Unmarshal(b, &c); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	c.applyDefaults()
	if err := c.validate(); err != nil {
		return nil, fmt.Errorf("config %s: %w", path, err)
	}
	return &c, nil
}

func (c *Config) applyDefaults() {
	if len(c.PortRange) == 0 {
		c.PortRange = []int{20000, 29999} // spec default (agent.md §3)
	}
	if c.CapacitySlots == 0 {
		c.CapacitySlots = 1 // unused by v0 run-once
	}
	if c.LogDir == "" {
		c.LogDir = "/var/log/birdman"
	}
	if c.DataDir == "" {
		c.DataDir = "/var/lib/birdman"
	}
}

func (c *Config) validate() error {
	if c.Region == "" {
		return fmt.Errorf("region is required")
	}
	if len(c.PortRange) != 2 {
		return fmt.Errorf("port_range must be [from, to], got %v", c.PortRange)
	}
	if c.PortRange[0] <= 0 || c.PortRange[1] > 65535 || c.PortRange[0] > c.PortRange[1] {
		return fmt.Errorf("invalid port_range [%d, %d]", c.PortRange[0], c.PortRange[1])
	}
	if c.CapacitySlots < 0 {
		return fmt.Errorf("capacity_slots must be positive, got %d", c.CapacitySlots)
	}
	if c.LimitsDefault.CPUMillis <= 0 || c.LimitsDefault.MemMB <= 0 {
		return fmt.Errorf("limits_default: cpu_millis and mem_mb must be positive")
	}
	if a := c.RegistryAuth; a != nil {
		if a.Username == "" || a.TokenFile == "" {
			return fmt.Errorf("registry_auth: username and token_file are required")
		}
	}
	return nil
}
